name: GunStick
version: 1.0
description: This causes guns to act like sticks?
author: herpingdo

main: me.herp.derp.GunStick.GunStick
commands:
  gs:
    description: Command to add and remove infinite ammo players. Syntax: /gs <add/remove/list> [name]